version: 1.2.8

endpoints:
  custom:
    - name: "ask"
      baseURL: "https://cc8e8c67-86e1-4406-b111-2ee0e380d077-00-75wtci6s9x0t.kirk.replit.dev"
      modelDisplayLabel: "RAG (Replit)"
      apiKey: "user_provided"
      models:
        default: ["ask"]
        chat: ["ask"]
      titleConvo: true
      titleModel: "current_model"

    - name: "noop"
      baseURL: "https://example.com"
      modelDisplayLabel: "Fake Model"
      apiKey: "user_provided"
      models:
        default: ["noop"]
        chat: ["noop"]
      titleConvo: false
      titleModel: "noop"
