version: 1.2.8

endpoints:
  custom:
    - name: "ask"
      apiBaseUrl: "https://cc8e8c67-86e1-4406-b111-2ee0e380d077-00-75wtci6s9x0t.kirk.replit.dev"
      modelDisplayLabel: "RAG (Replit)"
      apiKey: "system"
      apiType: "openai"
      isUserProvided: false
      titleConvo: true
      titleModel: "ask"
      models:
        default: ["ask"]
        chat: ["ask"]

    - name: "noop"
      apiBaseUrl: "https://example.com"
      modelDisplayLabel: "Fake Model"
      apiKey: "system"
      apiType: "openai"
      isUserProvided: false
      models:
        default: ["noop"]
        chat: ["noop"]
