version: 1.2.8
endpoints:
  custom:
    - name: "Customer Insights RAG"
      baseURL: "https://cc8e8c67-86e1-4406-b111-2ee0e380d077-00-75wtci6s9x0t.kirk.replit.dev"
      modelDisplayLabel: "Customer Call Analysis"
      apiKey: "system"
      models:
        default: ["ask"]
        chat: ["ask"]
      titleConvo: true
      titleModel: "ask"  # Use "ask" instead of "current_model"
      summarize: false
      forcePrompt: false
      dropParams: ["max_tokens", "user"]  # Clean up params that might conflict
