version: 1.0

endpoints:
  custom:
    ask:
      baseURL: https://cc8e8c67-86e1-4406-b111-2ee0e380d077-00-75wtci6s9x0t.kirk.replit.dev
      modelName: ask
      apiKey: ""
      titleConvo: true
      titleModel: ask
      iconURL: /chat-icons/openai.svg
      isUserProvided: false

models:
  default: [ask]
  chat: [ask]
  completion: [ask]
  all: [ask]

modelDisplayLabels:
  ask: RAG (Replit)
